substitutions:
  _BUCKET_NAME: 'inspire26_cloudbuild_artifacts'

steps:
  - name: 'ubuntu'
    id: Make-Gradle-Executable
    entrypoint: 'chmod'
    args: ['+x', './gradlew']
    waitFor: ['-']

  - name: 'gradle:8.5-jdk17-alpine'
    id: Run-Tests
    entrypoint: './gradlew'
    args: ['test', 'jacocoTestReport']
    dir: '.'  # <-- FIX: Run command in the project's root directory
    waitFor:
      - Make-Gradle-Executable

  - name: 'gradle:8.5-jdk17-alpine'
    id: Build-Application
    entrypoint: './gradlew'
    args: ['build', '-x', 'test', '--no-daemon']
    dir: '.'  # <-- FIX: Run command in the project's root directory
    waitFor:
      - Run-Tests

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Get-Docker-Password
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=dockerhub-password --project=inspire26 --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/docker-password.txt
    waitFor:
      - Build-Application

  - name: 'gcr.io/cloud-builders/docker'
    id: Docker-Login
    entrypoint: 'sh'
    args:
      - '-c'
      - 'docker login -u="aa061872" --password-stdin < /workspace/docker-password.txt'
    waitFor:
      - Get-Docker-Password

  - name: 'gcr.io/cloud-builders/docker'
    id: Build-Docker-Image
    args:
      - 'build'
      - '-t'
      - 'aa061872/store-app:$COMMIT_SHA'
      - '.'
    waitFor:
      - Docker-Login

  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Docker-Image
    args:
      - 'push'
      - 'aa061872/store-app:$COMMIT_SHA'
    waitFor:
      - Build-Docker-Image

artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/jacoco/$COMMIT_SHA/'
    paths: ['build/reports/jacoco/test/html/**']