# Google Cloud Build Trigger Configuration
# This file defines the trigger settings for automated builds

name: store-app-ci-cd
description: CI/CD pipeline for Spring Boot Store Application

# Trigger configuration
triggerTemplate:
  projectId: ${PROJECT_ID}
  repoName: ${REPO_NAME}
  branchName: main

# Build configuration
build:
  # Use the cloudbuild.yaml file
  steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        - 'builds'
        - 'submit'
        - '--config=cloudbuild.yaml'
        - '.'

# Substitution variables
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _REPO_NAME: ${REPO_NAME}
  _REGION: us-central1
  _IMAGE_NAME: store-app

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout
timeout: '1200s'  # 20 minutes

# Service account (optional - uses default if not specified)
# serviceAccount: projects/${PROJECT_ID}/serviceAccounts/${SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
