substitutions:
  _BUCKET_NAME: 'inspire26_cloudbuild_artifacts'

steps:
  # =============================================================================
  # == 1. Make gradlew Executable                                              ==
  # =============================================================================
  - name: 'ubuntu'
    id: Make-Gradle-Executable
    entrypoint: 'chmod'
    args: ['+x', './gradlew']
    waitFor: ['-']

  # =============================================================================
  # == 2. Apply Code Formatting Fixes                                          ==
  # =============================================================================
  - name: 'gradle:8.5-jdk17-alpine'
    id: Format-Code
    entrypoint: './gradlew'
    args: ['spotlessApply']
    dir: '.'
    waitFor:
      - Make-Gradle-Executable

  # =============================================================================
  # == 3. Run Unit & Integration Tests                                         ==
  # =============================================================================
  - name: 'gradle:8.5-jdk17-alpine'
    id: Run-Tests
    entrypoint: './gradlew'
    args: ['test', 'jacocoTestReport']
    dir: '.'
    waitFor:
      - Format-Code # Wait for formatting to complete

  # =============================================================================
  # == 4. Build the Application JAR                                            ==
  # =============================================================================
  - name: 'gradle:8.5-jdk17-alpine'
    id: Build-Application
    entrypoint: './gradlew'
    args: ['build', '-x', 'test', '--no-daemon']
    dir: '.'
    waitFor:
      - Run-Tests

  # =============================================================================
  # == 5. Retrieve Docker Hub Password from Secret Manager                     ==
  # =============================================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Get-Docker-Password
    entrypoint: 'bash'
    args:
        - '-c'
        - |
          gcloud secrets versions access latest --secret=MY_DOCKER_PASS --project=inspire26 --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/docker-password.txt
          cat /workspace/docker-password.txt
    waitFor:
        - Build-Application

  # =============================================================================
  # == 6. Login to Docker Hub                                                  ==
  # =============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: Docker-Login
    entrypoint: 'sh'
    args:
      - '-c'
      - 'docker login -u="aa061872" --password-stdin < /workspace/docker-password.txt'
    waitFor:
      - Get-Docker-Password

  # =============================================================================
  # == 7. Build Docker Image                                                   ==
  # =============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: Build-Docker-Image
    args:
      - 'build'
      - '-t'
      - 'aa061872/store-app:$COMMIT_SHA'
      - '.'
    waitFor:
      - Docker-Login

  # =============================================================================
  # == 8. Push Docker Image to Docker Hub                                      ==
  # =============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Docker-Image
    args:
      - 'push'
      - 'aa061872/store-app:$COMMIT_SHA'
    waitFor:
      - Build-Docker-Image

# =============================================================================
# == Optional: Specify artifacts to store (e.g., JaCoCo reports)             ==
# =============================================================================
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/jacoco/$COMMIT_SHA/'
    paths: ['build/reports/jacoco/test/html/**']